version: '3.1'
networks:
  backend:
    driver: bridge
services:
   db:
    image: postgis/postgis
    restart: always
    env_file:
      - postgis.env
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - 5432:5432
    networks:
      -  more-tech
      
   hack-api:
    build:
      context: ..
      dockerfile: LightFireMoreTech5.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:5000/
    ports:
      - "5000:5000"
    networks:
      -  more-tech
    depends_on:
      - db
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:5000/health || exit 1"
        ]
      interval: 30s
      timeout: 10s
      retries: 3

   #hack-redis:
   # container_name: my-hack-redis
   # image: redis:7.2-rc2
   # env_file:
   #     - .env
   # environment:
   #     - REDIS_PASSWORD=${DB_PASSWORD}
   # ports:
   #     - "5379:5379"
   # volumes:
   #     - redis-hack-data:/data
   # networks:
   #     - backend
   # restart: always

volumes:
  db-hack-data:
  redis-hack-data: