version: '3.1'
services:
  #microservices

  db:
    image: postgis/postgis
    restart: always
    env_file:
      - postgis.env
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - 5432:5432
    networks:
      -  more-tech
      
  hack-api:
    container_name: hack-backend
    build:
      context: ..
      dockerfile: LightFireMoreTech5.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:5000/
    ports:
      - "5000:5000"
    networks:
      -  more-tech
    depends_on:
      - db
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:5000/health || exit 1"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      
networks:
  more-tech:
    driver: bridge