version: '3.1'
services:
  #microservices

  db:
    image: postgis/postgis
    restart: always
    env_file:
      - postgis.env
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - 5432:5432
    networks:
      -  more-tech
      
networks:
  more-tech:
    driver: bridge